"""Deterministic Cartesian expansion of explicit scan axes."""

from __future__ import annotations

import copy
import itertools
from dataclasses import dataclass
from typing import Any

from scpc.scans.identity import RunIdentity, canonical_run_identity


@dataclass(frozen=True)
class ScanPoint:
    """One immutable experiment specification generated by a scan grid."""

    identity: RunIdentity
    coordinates: dict[str, Any]
    specification: dict[str, Any]


def _path_parts(path: str) -> tuple[str, ...]:
    parts = tuple(part for part in path.split(".") if part)
    if not parts or ".".join(parts) != path:
        raise ValueError(f"Invalid dotted configuration path: {path!r}")
    return parts


def _set_existing_path(document: dict[str, Any], path: str, value: Any) -> None:
    parts = _path_parts(path)
    current: dict[str, Any] = document
    for part in parts[:-1]:
        child = current.get(part)
        if not isinstance(child, dict):
            raise KeyError(f"Scan axis path does not resolve through a mapping: {path}")
        current = child
    leaf = parts[-1]
    if leaf not in current:
        raise KeyError(f"Scan axis path does not exist in the base configuration: {path}")
    current[leaf] = copy.deepcopy(value)


def expand_parameter_grid(
    base_specification: dict[str, Any],
    axes: dict[str, list[Any]],
    *,
    max_runs: int = 10000,
    identity_namespace: str = "scpc-background-v1",
) -> tuple[ScanPoint, ...]:
    """Expand explicit axes in stable lexical path order.

    Duplicate axis values that produce the same complete specification are
    rejected rather than silently scheduled twice.
    """

    if max_runs < 1:
        raise ValueError("max_runs must be positive")
    if not axes:
        identity = canonical_run_identity(base_specification, namespace=identity_namespace)
        return (
            ScanPoint(identity=identity, coordinates={}, specification=copy.deepcopy(base_specification)),
        )

    ordered_paths = tuple(sorted(axes))
    values_by_path: list[tuple[Any, ...]] = []
    run_count = 1
    for path in ordered_paths:
        _path_parts(path)
        values = axes[path]
        if not isinstance(values, list) or not values:
            raise ValueError(f"Scan axis {path!r} must contain a nonempty list")
        values_tuple = tuple(values)
        values_by_path.append(values_tuple)
        run_count *= len(values_tuple)
        if run_count > max_runs:
            raise ValueError(
                f"Cartesian scan contains {run_count} runs, exceeding max_runs={max_runs}"
            )

    points: list[ScanPoint] = []
    seen_hashes: set[str] = set()
    for combination in itertools.product(*values_by_path):
        specification = copy.deepcopy(base_specification)
        coordinates = dict(zip(ordered_paths, combination, strict=True))
        for path, value in coordinates.items():
            _set_existing_path(specification, path, value)
        identity = canonical_run_identity(specification, namespace=identity_namespace)
        if identity.sha256 in seen_hashes:
            raise ValueError(
                "Scan axes generate duplicate complete specifications; remove duplicate or equivalent values"
            )
        seen_hashes.add(identity.sha256)
        points.append(
            ScanPoint(
                identity=identity,
                coordinates=copy.deepcopy(coordinates),
                specification=specification,
            )
        )
    return tuple(points)
